### Criar uma nova task
POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "task 1",
  "description": "isso é uma descrição task"
}

### Listar tasks
GET http://localhost:3333/tasks?search=descri
Content-Type: application/json
