### Criar uma nova task
POST http://localhost:3333/tasks
Content-Type: application/json

{
  "title": "task 1",
  "description": "isso é uma descrição task"
}

### Listar tasks
GET http://localhost:3333/tasks
Content-Type: application/json

### Atualizar task
PUT http://localhost:3333/tasks/ca152a55-5e6d-4d7c-a2ec-380eb1d8e10a
Content-Type: application/json

{
  "title": "ATUALIZADA 1 task",
  "description": "ATUALIZADA isso é uma descrição task"
}

### Remover task
DELETE http://localhost:3333/tasks/31f3d9a0-a218-45bb-bc55-991a8843125d
Content-Type: application/json

### Completar task
PATCH http://localhost:3333/tasks/56af4e86-79b3-411a-8197-ef3b8ceb01da
Content-Type: application/json
